### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Maho91** [os-js/osjs-webdav-adapter#3]
I am trying to use the WebDAV adapter to mount Nextcloud, I followed the configuration as stated in the documentation. Below you can find my configs

client config
```
{
      name: 'nextcloud',
      label: 'nextcloud',
      adapter: 'webdav',
      attributes: {}
}
```

server config
```
{
      name: 'nextcloud',
      label: 'nextcloud',
      adapter: 'webdav',
      attributes: {
        connection: {
          uri: 'domain',
          username: '####',
          password: '####',
          access_token: null,
          prefix: '/remote.php/webdav/'
        }
}
```

server index
```
import {
  Core,
  CoreServiceProvider,
  DesktopServiceProvider,
  VFSServiceProvider,
  NotificationServiceProvider,
  SettingsServiceProvider,
  AuthServiceProvider
} from '@osjs/client';

import {PanelServiceProvider} from '@osjs/panels/';
import {GUIServiceProvider} from '@osjs/gui';
import {DialogServiceProvider} from '@osjs/dialogs';
import * as config from './config.js';
import {WidgetServiceProvider} from '@osjs/widgets';
import {WirelessToolsServiceProvider} from '@osjs/wireless-tools-provider';
import MyCustomLogin from './custom-login.js';
import webdavAdapter from '../packages/osjs-webdav-adapter/index';

const init = () => {
  const osjs = new Core(config, {});

  // Register your service providers
  osjs.register(CoreServiceProvider);
  osjs.register(DesktopServiceProvider);
  osjs.register(VFSServiceProvider, {
    args: {
      adapters: {
        webdav: webdavAdapter
      }
    }
  });
  osjs.register(NotificationServiceProvider);
  osjs.register(SettingsServiceProvider, {before: true});
  osjs.register(AuthServiceProvider, {before: true,args: {
      login: (core, options) => new MyCustomLogin(core, options)
    }});
  osjs.register(PanelServiceProvider);
  osjs.register(DialogServiceProvider);
  osjs.register(GUIServiceProvider);
  osjs.register(WidgetServiceProvider);
osjs.register(WirelessToolsServiceProvider);
  osjs.boot();
};


window.addEventListener('DOMContentLoaded', () => init());
```

When I click on the mounted nextcloud path I am getting this error message "TypeError: t.readdir(...).then is not a function". 

Thank you in advance

**Comment by andersevenrud** [comment]
The problem here is that you added the adapter to the client. It's a server VFS adapter :) 

I probably should make that a bit more obvious.... it's only described as such in the description of the repo, which is not enough :thinking:

**Comment by Maho91** [comment]
I removed the adapter from the client, now I am getting this error "Error: An error occured while performing a request: Error: TypeError: Cannot read property 'attributes' of undefined
    at http://127.0.0.1:8000/vendors~osjs.js:290:74439". 

where my client configs are :

`{
        name: 'nextcloud',
        label: 'nextcloud',
        attributes: {}
 }`

and client's index is: 
`osjs.register(VFSServiceProvider);`

as for the serves are the same. any Ideas?

**Comment by andersevenrud** [comment]
> where my client configs are :

Is that the entirety of your config file ? Because it should not look like that.

> as for the serves are the same

You want to use the webDav adapter on your server.

> any Ideas?

It should be pretty straight forward

1. Add the adapter to the server provider
2. Add a new mountpoint to your client config
3. Add a new mountpoint to your server config

**Comment by andersevenrud** [comment]
Also, remember to rebuild the client after changing configs/bootstrap :)

**Comment by andersevenrud** [comment]
I think you might have found a bug here... I'll get back to you ASAP on this.

**Comment by andersevenrud** [comment]
I've published a new version of this adapter now (`1.0.4`) that should fix your issues.

What I found was:

1. There was a typo in the README. Adapter property should have been `webdav` not `owncloud`
2. I had forgotten to commit some changes related to updates to the `@osjs/server` module

If you run `npm update @osjs/webdav-adapter` and make sure you correct the adapter property, you should no longer get those errors.

**Comment by Maho91** [comment]
Hi Anders thanks a lot man you have solved it with your new update, it works now. Thanks again for your help ^_^.

**Comment by Maho91** [comment]
Dear Anders, 

now osjs mounts the Nextcloud street forward, but the first letter of every element is cutoff. as well as the files are not opening normally and when I open a directory it is giving the below error:
"Error: An error occured while performing a request: Error: TypeError: Cannot read property 'getElementsByTagNameNS' of undefined"

**Comment by andersevenrud** [comment]
I sadly don't have time to look into this until tomorrow as I haven't have time to read this until now and I'm heading to bed. I'll get back to you on this ASAP.

**Comment by andersevenrud** [comment]
Something dawned on me.

Could you try replacing

```
          prefix: '/remote.php/webdav/'
```

with:

```
          prefix: '/remote.php/webdav'
```

That might actually fix your issue.

**Comment by andersevenrud** [comment]
I quickly tested this myself and was able to reproduce. I puslished a new version (`1.0.5`) that takes care of that backward slash :)

**Comment by Maho91** [comment]
Everythings work perfectly, thanks man.
